kind: Service
apiVersion: v1
metadata:
  namespace: momo-system
  name: bms-authority-service
  labels:
    app: bms-authority-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: bms-authority-service
  type: ClusterIP
