spring:
  cloud:
    gateway:
      routes:
        - id: index
          predicates:
            - Path=/index
          uri: lb://bms-authority-service
      default-filters:
        - RequestBody
        - ResponseBody