kind: Service
apiVersion: v1
metadata:
  namespace: momo-system
  name: bms-gateway
  labels:
    app: bms-gateway
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: bms-gateway
  type: ClusterIP
